project:
  type: website
  output-dir: docs

website:
  title: "Teaching"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sessions-tab/sessions-index.qmd
        text: Sessions
    logo: images/logo_tepak.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

knitr:
  opts_chunk:
    comment: "#>"
    collapse: true
    echo: false

