project:
  type: website
  output-dir: docs

website:
  title: "Teaching"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sessions.qmd
        text: Sessions
    logo: images/logo1.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

knitr:
   opts_chunk:
     fig.path: "images/"
     comment: "#>"
     collapse: true


